name: Smart Money Daily Email

on:
  workflow_dispatch:

  schedule:
    # GitHub cron uses UTC.
    # During Mountain Daylight Time, these are about:
    # 7:00 AM, 1:00 PM, and 7:00 PM Mountain Time.
    - cron: "0 13,19,1 * * *"

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run app
        env:
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
          EMAIL_APP_PASSWORD: ${{ secrets.EMAIL_APP_PASSWORD }}
        run: python app.py
